name: ðŸš€ Auto Deploy to VPS

on:
  push:
    branches:
      - master  # faqat main branch push boâ€˜lganda ishga tushadi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # === 1. Repositoryni olish ===
      - name: Checkout repository
        uses: actions/checkout@v4

      # === 2. Java versiyasini oâ€˜rnatish ===
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      # === 3. Projectni build qilish (Gradle bilan) ===
      - name: Build project
        run: ./gradlew clean build -x test

      # === 4. Docker Hub login ===
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      # === 5. Docker image yaratish ===
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME}}/bron-app:latest .

      # === 6. Docker imageâ€™ni push qilish ===
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME}}/bron-app:latest

      # === 7. VPS serverga deploy qilish ===
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/bron

            docker compose down

            docker pull ${{ secrets.DOCKER_HUB_USERNAME}}/bron-app:latest

            echo "ðŸš€ Starting new containers..."
            docker compose up -d --build

            echo "âœ… Deployment completed successfully!"
